# Generated by Django 4.2.11 on 2024-04-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_booked_to_property_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='booked_to',
        ),
    ]
