# Generated by Django 4.2.11 on 2024-03-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%y/%m/%d')),
                ('address', models.TextField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('availableFrom', models.DateField()),
                ('furnished', models.BooleanField(default=False)),
                ('lease', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
