# Generated by Django 4.2.11 on 2024-03-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0002_remove_property_image_houseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to='house_images/'),
        ),
    ]
